networks:
  intranet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/24
          gateway: 172.1.0.1
          
services:
  selenium-standalone-chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    hostname: chrome
    networks:
      intranet:
        ipv4_address: 172.1.0.4
    ports:
      - 4444:4444
      - 7900:7900
    privileged: true
    shm_size: 2g
    environment:
      - PASSW=secret

  fastapi-app:
    image: fastapi_celery_example_web
    container_name: fastapi
    hostname: fastapi
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8002:8002
    restart: always
    environment:
      - IP_SELENIUM=172.1.0.4
      - PORT=4444
    networks:
      intranet:
        ipv4_address: 172.1.0.3