networks:
  intranet:
    driver: bridge

services:
  selenium-standalone-chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - intranet
    ports:
      - 4444:4444
      - 7900:7900
    privileged: true
    shm_size: 2g

  fastapi-app:
    image: fastapi_celery_example_web
    container_name: fastapi
    hostname: fastapi
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8002:8002
    restart: always
    networks:
      - intranet