FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN git clone https://github.com/lcrochaDEV/web-intra-python

COPY . .

CMD uvicorn app:app

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]


#INSTALAÇÃO python, fastapi, uvicorn, selenium
